### ISSUE TITLE
Patreon podcasts won't play on Android Automotive and Chromecast

### ISSUE THREAD

**Issue by ashiagr** [Automattic/pocket-casts-android#272]
A user in 5514912-zen reported that Patreon podcasts won't play on Android Automotive and Chromecast.

On Chromecasting an episode from a Patreon podcast, 
> The pocket casts app launches, shows the album art but after a few seconds goes back to the splash screen.

The logs contain following error:
> can't startForeground as the notification is null

##### This could be a device specific issue as the user is able to play the episode on nest mini but could not on nest hub.

**Comment by joashrajin** [comment]
5720971-zd-woothemes - Patreon podcasts not working in Android Automotive

Ref: p1669797054345289-slack-C02A333D8LQ

**Comment by CameronMilliken** [comment]
This bug is STILL existing, causing me to uninstall and reinstall at least 5 times a week. As a paid member, can I ask that this be escalated?

5720971-zen

**Comment by reginabally** [comment]
Hi @ashiagr 👋 Given the number of reports after [this potential fix](https://github.com/Automattic/pocket-casts-android/issues/272#issuecomment-1236604318), what can we (and the user) do to help with the troubleshooting? Thanks!

**Comment by ashiagr** [comment]
There are two separate issues that are captured in this thread:

1. Casting issue to a chromecast device/ nest speakers from phone
2. Unable to play podcasts via patreon in automotive

Most of the issues in this thread are related to the first (casting) issue which got resolved in PR #280.

For the second one,  I see in the video linked in 5720971-zen, [this error](https://github.com/Automattic/pocket-casts-android/blob/7afa3d70e9a4bc2370594bcbc09d2c0c7f3dcefc/modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt#L876-L877):

 > "Could not load podcast. Please check your internet connection and try again."

I see it is due to `HttpDataSource.HttpDataSourceException` and not due to a casting connection issue. Unfortunately, at this time, I cannot figure out the full exception details as it is not being logged anywhere. I'll put some logging code around that area in an upcoming version and we'll investigate it from there.

Thanks for your patience. 🙏

**Comment by joelfreak** [comment]
I am still having this issue, it happened today again. Any word on a fix?

Reid

**Comment by ashiagr** [comment]
Not yet @joelfreak. We're unable to reproduce the issue here and are trying to get error logs from Automotive production app for playback errors. You cannot send them using email support on Automotive. 

Can you tell us if the issue happens with all Patreon feeds or a specific one? Do non-Patreon feeds always play fine for you? I'm asking it as the original issue was not limited to Patreon feeds, it had to do something with the casting connection which broke while we upgraded the casting SDK but it was fixed later on. 

We do not have many reports of Patreon feed not playing on Automotive which makes it difficult to investigate. There's a possibility that the problematic feed is not supported properly on the platform by the [media library](https://github.com/google/ExoPlayer/issues) but that's just speculation until we see the logs.

From the video you shared, we noticed there was a network connection issue at one point:

<img width=320 src="https://user-images.githubusercontent.com/1405144/230065227-bf08ef24-b0af-4699-a088-c8bb38e36b05.png"/>

but we also noticed that the play button was unresponsive at times. If you could tell us any pattern, that might help us fix the issue.

**Comment by joelfreak** [comment]
It usually happens while I am driving, so I should always have
connectivity at that time. I would be listening to some other podcast, and
the next one in my list will come up, and nothing will play. I will finally
get a chance to see what is happening, and it will be the error you see
above. How can I send you logs from the Android Automotive client? I
generally listen to one single podcast 60% of the time, so I see it happen
with that podcast more often, I don't remember if I have seen it with any
other.

Reid

**Comment by ashiagr** [comment]
@joelfreak, thanks for sharing the details. We’re working on adding an easy option to send debug logs from the automotive app.

**Comment by joelfreak** [comment]
I see the change made in the version log, but I don't see how to use it?

Reid

**Comment by ashiagr** [comment]
Currently, the option is only available in the mobile app. Could you tell us the exact podcast + episode that you played recently (preferably in the latest automotive app release >= 7.38) that caused this issue? We could try locating it in the crash reporter tool.

**Comment by joelfreak** [comment]
I have not had it YET on this version. I will keep an eye out for it.

Reid

**Comment by joashrajin** [comment]
> I’ve been using Pocket Casts to play podcasts while driving, and mostly it’s worked fine, but recently a paid Patreon/RSS-fed podcast has stopped working.
The car is signed into the same account as my phone, and keeps both synced across devices as I play things, but the car can no longer play paid podcasts. I don’t see anything in the car’s settings to reset the cache or anything like that, but I’ve been unable to play the podcasts I pay for for a couple of a weeks now.
Any ideas on how I can get this sorted on my Android/Volvo head unit?

6284458-zd-woothemes

**Comment by joelfreak** [comment]
I just had a bug reoccurrence. How can we debug?

Reid

**Comment by ashiagr** [comment]
Reid 👋 
Could you tell us the app version and podcast + episode name?

**Comment by joelfreak** [comment]
It happens on Good Day Internet, the same private Patreon URL I sent
earlier on this thread. It happens on random episodes, today it happened on
4495. I am running 7.39-rc-2a (59096).

Reid

**Comment by ashiagr** [comment]
We searched for the episode https://pca.st/episode/7908ac29-26fe-4266-932a-08f777de1541 and could not find any crashes associated with it. At this time, we do not have enough data to reproduce this issue. 

We kindly request your patience as we work towards implementing a device log-sharing feature in the Automotive app. Due to other pressing priorities, we have been unable to actively focus on adding it.

**Comment by joelfreak** [comment]
I posted a video of the error occurring. Can you view that?

Reid

**Comment by joelfreak** [comment]
This just keeps happening. Can this PLEASE be escalated?

Reid

**Comment by joelfreak** [comment]
This is STILL happening. Can someone please address it?

Reid

**Comment by joelfreak** [comment]
Please tell me when I can expect to see this version in my beta channel. I
am happy to share logs when I have them. The other thing that would be
useful is to somehow reset the cache...when the player errors out trying to
play a file, there is NO WAY to ever play that again without uninstalling
and reinstalling the app...if there was a way to just 'forget' it and try
again, that would be great.

Reid

**Comment by mchowning** [comment]
> Please tell me when I can expect to see this version in my beta channel.

I expect it to be released sometime next week.

> if there was a way to just 'forget' it and try again, that would be great.

When you sign into or out of the automotive app there's an option to clear data. Try clearing data when you sign out and then sign back in and that should give you a clean start.

<details><summary>Clear data dialog</summary>

![image](https://github.com/Automattic/pocket-casts-android/assets/4656348/ca8bb2fd-5647-4e01-8ebf-cbb98fdaade0)


</details> 

Does uninstalling and reinstalling always fix the problem (at least temporarily), or is it still hit and miss even after that?

Also, do you usually see the network error message (shown in https://github.com/Automattic/pocket-casts-android/issues/272#issuecomment-1497328444) when the problem occurs?

**Comment by mchowning** [comment]
Thanks for the info @joelfreak .  I can imagine how frustrating this issue is, and I appreciate your help.

> Uninstalling and reinstalling fixes it 100% of the time.

That's helpful, and rules out some possible causes. 

So just making sure I understand correctly... You're driving, and the problem occurs. Obviously, you're not uninstalling while you're driving. Once you stop, the problem still happens if you try to play the same episode. If you uninstall and reinstall the app right then, though, the problem is immediately gone for that episode. 

I'm basically just wanting to make sure that there is nothing else that changes between the time the problem occurs and the time when uninstalling and reinstalling fixes the issue.

Let me pepper you with some more questions just to try to gather as much info as possible since we're having trouble tracking this issue down.

Have you noticed any other patterns on which podcasts this happens with? For example, does this only occur with Patreon podcasts and no other podcasts, and does it occur on all Patreon podcasts or only certain ones?

Did you have some podcasts that were working fine, and then suddenly they started having this issue? Did you start having this issue across multiple podcasts at the same time, or have different podcasts worked fine at different times? If any podcasts were working fine for a time and then suddenly started having this issue, do you remember if you changed cars or update your headunit software around the time the issue started occurring?

I believe you mentioned that the issue also occurs on wifi. Can the issue occur on one connection (i.e., mobile data) and then the issue does not resolve for that episode even after you switch to another connection (i.e., wifi)?

Since you've been uninstalling and reinstalling the app to resolve the issue, I assume that restarting the headunit or the car's modem does not resolve the issue.

Sorry for all the questions, just trying to narrow down the possible issues as much as possible.

**Comment by joelfreak** [comment]
I caught it happening and got a log. It seems like you are getting a 403
error (see logs) but it's fake. As soon as I reinstall, it can get the
episode just fine.

Reid

**Comment by joelfreak** [comment]
Here it is after a reinstall, playing just fine.

Reid

**Comment by igotdes** [comment]
@mchowning The forum user you were helping out [here](https://forums.pocketcasts.com/forums/topic/unable-to-play-private-patreon-podcasts-when-casting-to-google-home/) has reported back that things have been going well for them lately:

> I don’t know what’s changed, but it seems like this has resolved itself. All my Patreon feeds are advancing and playing over Google Home like I would expect.
>
> Thanks to you and the team for the time you spent on this.

**Comment by joelfreak** [comment]
Same problem, keeps happening even with new version. Please, can someone
please address this.

Reid

**Comment by joelfreak** [comment]
It happened yet again. You can copy logs in automotive, however Google
doesn't have any app you can paste them into...can this PLEASE get
escalated?

Reid

**Comment by joelfreak** [comment]
Is anyone even reading these?

Reid

**Comment by CookieyedCodes** [comment]
@joelfreak I think Matt was on holidays last week, if he doesn't respond in a week @ him 😉

**Comment by ashiagr** [comment]
👋 @joelfreak 

> Google doesn't have any app you can paste them into

Whenever it happens again, could you take screenshots of the logs from your phone and share them with us as explained [here](https://support.pocketcasts.com/contact-us/)? If we could also get answers to the questions that Matt asked in https://github.com/Automattic/pocket-casts-android/issues/272#issuecomment-1679290798, that might also help.

**Comment by joelfreak** [comment]
Android AUTOMOTIVE has no app to paste the logs back into. I can only take
the pictures and send them, which I have IN THIS TICKET.

Reid

**Comment by joelfreak** [comment]
The problem keeps occurring on the same episode of the show once it
happened once. It also appears to happen on multiple episodes of that show
until a reinstall, as I showed in the log from yesterday.
It mostly occurs on the DTNS podcast, but I have had it appear on other
podcasts. This makes sense as DTNS is more than 80% of my podcasts I listen
to (its the only daily show)
I can FORCE this to happen if I somehow try to start a new podcast while
having no internet access, however it doesn't only happen when there is no
internet. This error can happen, and I can flip to another app on the car,
and it will work just fine. The error on the car will keep happening until
reinstallation.
I have had this bug since day 1.

Reid

**Comment by mchowning** [comment]
> Android AUTOMOTIVE has no app to paste the logs back into. I can only take
the pictures and send them, which I have IN THIS TICKET.

I'm not seeing any pictures or video showing the logs from Android Automotive. Are you saying you have included those somewhere? This thread has gotten long, so maybe I'm overlooking them. If so, would you mind linking to them?

You can access the logs in recent versions of our Android Automotive app (https://github.com/Automattic/pocket-casts-android/pull/1277 by going to ⚙️ → `About` → `Logs`.

**Comment by joelfreak** [comment]
I post pictures of the logs on EACH AND EVERY email I have sent in for the
last 3-4 posts. Is there an email I can send them to where maybe we can get
them to the thread otherwise? [image: PXL_20231001_183423024.jpg][image:
PXL_20231001_183434246.jpg] Here are the last 2 photos from yesterday.

Reid

**Comment by joelfreak** [comment]
This is Joelfreak from my git account. Lets see if this works. 
![PXL_20231001_183423024](https://github.com/Automattic/pocket-casts-android/assets/19534665/af9c0934-7eb6-4198-94a8-aa0c98bcdd05)
![PXL_20231001_183434246](https://github.com/Automattic/pocket-casts-android/assets/19534665/0967bd70-9873-41f4-9a7c-9c3892e58efb)
These are the latest logs from this last occurrence.

**Comment by mchowning** [comment]
That worked. Thanks!

**Comment by joelfreak** [comment]
Just to be clear, I understand if Android Auto isn't perfect, and theres some burp in the internet, and the file cant be loaded...its odd, but ok. My MAIN problem here is the program CANNOT recover from it, and needs to be completely reinstalled to ever play that file again.

**Comment by mchowning** [comment]
The logs you sent show that we're getting a 403, which indicates that the server is saying the call is not authorized. That would make me think the problem is something weird with Patreon if it weren't for the fact that uninstalling and reinstalling the app fixes it.

There is this StackOverflow question of some people having a similar issue, but there's no clear solution and the possible issue discussed there (different cookie managers) doesn't seem to apply since we don't have any special cookie handling that I'm aware of. Any thoughts @geekygecko or @ashiagr ?

**Comment by joelfreak** [comment]
It keeps happening. Can SOMEONE please address this? 
![PXL_20231012_183042907](https://github.com/Automattic/pocket-casts-android/assets/19534665/0672a79c-5ede-48ef-9171-308db800d646)

**Comment by yaelirub** [comment]
@joelfreak. Thank you for sharing all of the details and screenshots. I can imagine how frustrating it must be. I can guarantee you that we will prioritize this issue and provide an update as soon as possible.

**Comment by mchowning** [comment]
We have merged a fix that should solve the issue of Patreon podcasts sometimes failing to play on Android Automotive. It will be released in `7.53`, and a part of the `7.53` beta builds, which we will publish early next week.

**Comment by McPhale** [comment]
I've started having this same casting problem this week (maybe last week?) and found this issue. Eg, casting any patreon (downloaded) podcast to a google cast device will randomly stop working, at which point no other patreon feeds will cast.  Clearing cache+data and re-installing the app is the only thing that will fix it, and I've had it stop working again less than 24 hours after a re-install.  

Should I open a new issue? I'll hold off on supplying logs and version info until that's determined.

Thanks!

**Comment by geekygecko** [comment]
@McPhale in version 7.76 there was a fix for Chromecast to help with the issue of our foreground service stopping. I'm guessing you are already using this version that is in production. 

This sounds slightly different in that it only happens with Patreon. Chromecast works by streaming the episode from the author's server, so it won't be affected if you download the episode to your device locally. If you cast another episode that isn't from Patreon, does it work? 

Would you mind emailing your logs and including my name (Philip)? I will see if there is anything in there that helps us fix this problem you are experiencing. Thanks for reporting this.

**Comment by McPhale** [comment]
@geekygecko Will do, I'll get a repro together for you this evening :) And yes,  it only occurs on patreon feeds; normal feeds continue to work normally.  Thank you!

**Comment by McPhale** [comment]
@geekygecko My phone received the android 15 update right after I commented, and I have not been able to reproduce the issue since then.  I'll follow up if I start seeing the behavior again
