### ISSUE TITLE
Add to F-Droid

### ISSUE THREAD

**Issue by licaon-kter** [Automattic/pocket-casts-android#424]
I see some stuff that needs to be separated under a gradle flavor (google services, cast, firebase, billing. oss-license: as these are either not FOSS or depend on not-FOSS libs). Sentry/Tracks is ok but it might warrant a `Tracking` antifeature if not opt-in.

A custom maven repo is used for which dep (Automattic-Tracks)? That [is FOSS](https://github.com/Automattic/Automattic-Tracks-Android). Is it available in other repos, eg. Maven Central? Or we need to build it.

/LE: updated deps info

**Comment by eighthave** [comment]
As an F-Droid contributor, I'm here to offer my help getting Pocket Casts to be free software.

**Comment by xrishox** [comment]
would love to see this project added to fdroid

**Comment by IzzySoft** [comment]
Still not even a response from the team? Third F-Droid contributor here. There's already an [inclusion request](https://gitlab.com/fdroid/rfp/-/issues/2236) open with us for several month which we cannot proceed with, as we'd need your help. Count the thumbs how many folks wait to see your app there, doesn't that convince you it should be included? You were even offered a hand for that. So may I kindly ask you to join the efforts? Thanks in advance – @mchowning & all!

**Comment by mchowning** [comment]
Thanks for following up @IzzySoft . This had fallen off my radar.

It would be great to see Pocket Casts on F-Droid, but unfortunately this is not a focus for the core team at this time. I'm happy to help move this forward and do what I can unblock anyone who wants to work on this though. 

What do you think would be the best first steps? Is there anything you need to unblock this work?

> I see some stuff that needs to be separated under a gradle flavor (google services, cast, firebase, billing. oss-license: as these are either not FOSS or depend on not-FOSS libs). 

How would we go about separating these? Something like calling a wrapper around these libraries that has a noop implementation in the f-droid build flavor, or something else?

> Sentry/Tracks is ok but it might warrant a Tracking antifeature if not opt-in.

Just applying the Tracking anti-feature flag sounds like the best option at this time to me.

**Comment by IzzySoft** [comment]
Thanks for your reply, @mchowning! I'm not an Android dev myself, so I cannot speak for "proper implementation" nor how to set up build flavors (I've seen that a lot, though, that `build.gradle` e.g. had `gplayImplementaion` for Firebase to keep it out of the `foss` flavor – and maybe `fossImplementation` for a dummy). If you'd need a dummy, it should better not have the same "paths" (e.g. the "stub" should not have the same package name, as that would lead to "false alerts" in the scanners). At least if it can be avoided.

As for the `Tracking` AF: why not making Sentry opt-in instead? Have a bool setting for that initiated with NULL, so on first start the user is asked for consent – and later can correct the decision via the settings of the app)? That would avoid the AF. Again, that can also be done flavor-wise – though I'd recommend opt-in always (also GDPR-wise).

Now reaching the top: first steps. I didn't work on that RFP, it just came to my attention in one of my triage runs. Let me take a quick look…

1. moving Billing and GMS with the install referrer, Firebase etc. to a `gplay`flavor to keep them out of the `foss` build, as those two are show-stoppers for F-Droid
2. making Sentry opt-in
3. setting up Fastlane (I can help with that step – or you could use my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688) for guidance)

As for cloud messages: you might wish to take a look at [UnifiedPush](https://unifiedpush.org/), which is a FOSS way to achieve that. For your Playstore release (`gplayImplementation`), you could bundle their FcmDistributor, so folks there wouldn't even notice a difference – while shipping the `foss` flavor entirely without distributor, and folks can pick the one they prefer (see e.g. [Push Clients/Manager](https://android.izzysoft.de/applists/category/named/network_push) – several apps at F-Droid do so already). That could be implemented in a second step, once flavors are set up and all is ready (i.e. the first FOSS release might simply come without, one of the next will fill it in – so you don't have to do all of it at once).

**Comment by eighthave** [comment]
@mchowning would you accept a pull request that adds a "free" build flavor that removes the proprietary libraries?  Then there will be a build flavor for the current state, whatever you want to call that.  It is often called "play" after Google Play.

**Comment by mchowning** [comment]
> @mchowning would you accept a pull request that adds a "free" build flavor that removes the proprietary libraries? Then there will be a build flavor for the current state...

👍 We would gladly accept PRs toward that! I do think that getting to a fully free build flavor will require quite a few changes, so I just ask that the work be broken up into separate PRs where possible so that it's easier to review and test the PRs.

**Comment by eighthave** [comment]
I just took a quick look.  I agree, the best approach here should be to chip away at it in multiple merge requests.  I just submitted the first, which defines the _gplay_ and _free_ build flavors, based on well honed setups in Nextcloud, Element, and other apps.
https://github.com/Automattic/pocket-casts-android/pull/1206

**Comment by MiSikora** [comment]
@IzzySoft @eighthave Could you explain how this would work in principle? Let's say we have a build variant that is free of not FOSS dependencies. Who would build this version and upload it to F-Droid? What about signing the app?

**Comment by licaon-kter** [comment]
> Who would build this version

F-Droid would build it
> What about signing the app?

If the app is build reproducible ( https://f-droid.org/docs/Inclusion_How-To/#reproducible-builds ) the F-Droid would host the version from upstream, eg. they will upload the FOSS version here too: https://github.com/Automattic/pocket-casts-android/releases/tag/7.72

**Comment by MiSikora** [comment]
How F-Droid could build it without having access to our signing key?

**Comment by qoheniac** [comment]
Apps that aren't reproducable in the sense above are built and signed by F-Droid.

**Comment by MiSikora** [comment]
Ok, thanks for the clarification.

I don't think we have the resources to support that, and it would make more sense, in my opinion, to create a FOSS fork. Many of our features rely on Google services. Abstracting and/or modularizing things to work with FOSS would require significant effort. Even if we have external contribution to make it initially work, maintaining FOSS compliance would also be a substantial workload. Additionally, designing new features or enhancing existing ones could become problematic. Then there's the issue of testing code changes.

However, I'd love to hear thoughts from the rest of the @Automattic/pocket-casts-android team before proceeding with anything.

**Comment by licaon-kter** [comment]
@MiSikora please read the link....

and https://f-droid.org/docs/Reproducible_Builds/ branches YES and YES

**Comment by MiSikora** [comment]
I'm not saying they can't be removed or replaced. I don't even know what are the possible FOSS alternatives. I'm saying it requires maintenance from our team as we develop the app.

In the original message a few libraries are listed.

> google services, cast, firebase, billing. oss-license

Off the top of my head this means that the code related to subscriptions, Chrome Cast, in-app review, Google authentication, library listing would need to go away or changed.

**Comment by erebion** [comment]
For many other apps what's done is to just leave out everything that relies on those proprietary libraries.

Then what would we lose? Chromecast support and... what else?

**Comment by erebion** [comment]
Also, VLC use a FOSS library for Chromecast support: 

https://mfkl.github.io/chromecast/2018/10/21/High-performance-cross-platform-streaming-with-libvlc-and-Chromecast-on-.NET.html

**Comment by eighthave** [comment]
I'm happy to support you in this process, since I see Automattic as a key ally in free software.  F-Droid contributors like @IzzySoft @licaon-kter and I now have extensive experience helping companies manage a FOSS flavor (Element/Matrix, Nextcloud, Mozilla, Wire, Proton, Threema, VLC, Mullvad, IVPN and more).

In terms of implementation and maintenance, my pull request #1206 already handles the Chrome Cast case.  The merge conflicts from build system changes since I implemented it, and do not in my opinion mean that there would be additional maintenance load.  The flavor could would be in place when the build system is refactored.

**Comment by MiSikora** [comment]
@eighthave First of all, thank you for your willingness to help with the FOSS variant.

I checked the code in #1206, and from my understanding, Chromecast is not fully handled. While `CastOptionsProvider` was removed, the `com.google.android.gms:play-services-cast dependency` is still present in the APK because it is used by many other classes that end up in the final binary.

Please don't get me wrong - I am not opposed to having a FOSS-compliant build in principle. In fact, I think it would be fantastic! However, achieving this is quite challenging due to the heavy coupling of our code with non-FOSS libraries. Even if we had a FOSS-compliant version, we would still need to maintain it, ensure that nothing breaks, and develop features with FOSS compliance in mind. At this moment, I don't believe we have the resources for such an effort.

That said, I'll discuss this internally with the team. If we make any decisions, I'll be sure to let you know.

**Comment by MiSikora** [comment]
After discussing this internally, we have decided not to proceed with including a FOSS variant of Pocket Casts in our GitHub repository at this time.

We do not have the resources to maintain such a variant. I respectfully disagree with the assessment that maintaining a FOSS version would involve minimal effort. The proposed use of "shim classes," for example, is not as straightforward as it might seem. Any changes or deprecations in the non-FOSS libraries would require corresponding updates to these shims, introducing ongoing maintenance challenges and potential risks.

While alternatives such as modularization, encapsulation, and dependency injection are viable, they come with their own substantial costs. Implementing these solutions would require significant restructuring of our codebase. And in cases of some of the features it would be inevitable. Additionally, maintaining a FOSS variant would necessitate continuous infrastructure support, regular development considerations, and more testing. This is simply not feasible for us alongside our current development priorities.

If there is strong interest in a FOSS version, we encourage those who are passionate about this to fork the project and maintain it independently. This approach would allow the community to create and manage a FOSS-compliant version without placing an additional burden on our team. If, as suggested, the effort is minimal, maintaining such a fork should be manageable.

Thank you for your understanding.
